version: '3.9'

services:
  db:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: u1rkXHAJzyDtFvo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
